### PR TITLE
Add DelayCommits

### PR DESCRIPTION
**Pull request by roed314**
I added DelayCommits to the functions in `student.py` that looked like they needed them.  I may have missed some, and I'm not sure what a good way to test these changes is....

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
@roed314 Thanks!  Looking at this I'm thinking that it might be simpler/safer to simply wrap all of the functions that make updates, even if they don't currently need them, unless there is a downside to doing so?  But I can take care of that.

**Comment by AndrewVSutherland** [comment]
@roed314 I wrapped all the public methods of the Student class that make database updates with DelayCommits (I also changed dbwrapper to implement aliasing the test table names properly so that DelayCommit can access all the attributes of db._db -- I actually think aliasing is a common enough use case that it might be worth adding this functionality to psycodict).

**Comment by roed314** [comment]
I don't think there's a downside to wrapping all of the update calls with `DelayCommit`.  I'm not sure what you mean about aliasing test table names properly.  Can you point to the part of `dbwrapper.py` that you're referring to?

**Comment by AndrewVSutherland** [comment]
See the getdb() function which returns either the actual db object or a PSetPartnersTestDB object that behaves exactly like the actual db object except it redirects all references to the tables students, groups, classlist, grouplist, messages to the tables test_students, test_groups, test_classlist, test_grouplist whenever livesite returns false.

**Comment by AndrewVSutherland** [comment]
But in general I can imagine wanting a method db.alias("foo","bar") that would modify the db object so that all rreferences to the table foo get redirected to bar.

**Pull request merged**
